"""time_location_coupon

Revision ID: 72a2413a6e22
Revises: 7fbdcd1f9f75
Create Date: 2020-10-04 03:27:11.823021-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a2413a6e22'
down_revision = '7fbdcd1f9f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('coupon', sa.Column('dress_scanned_date', sa.DateTime(), nullable=True))
    op.add_column('coupon', sa.Column('dress_scanned_location', sa.String(), nullable=True))
    op.add_column('coupon', sa.Column('hair_scanned_date', sa.DateTime(), nullable=True))
    op.add_column('coupon', sa.Column('hair_scanned_location', sa.String(), nullable=True))
    op.add_column('coupon', sa.Column('makeup_scanned_date', sa.DateTime(), nullable=True))
    op.add_column('coupon', sa.Column('makeup_scanned_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'makeup_scanned_location')
    op.drop_column('coupon', 'makeup_scanned_date')
    op.drop_column('coupon', 'hair_scanned_location')
    op.drop_column('coupon', 'hair_scanned_date')
    op.drop_column('coupon', 'dress_scanned_location')
    op.drop_column('coupon', 'dress_scanned_date')
    op.drop_column('coupon', 'created_date')
    # ### end Alembic commands ###
