"""auto2

Revision ID: 7336f71b8752
Revises: d14fe5934836
Create Date: 2021-03-07 05:51:21.864901-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7336f71b8752'
down_revision = 'd14fe5934836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
