"""auto

Revision ID: d14fe5934836
Revises: 72a2413a6e22
Create Date: 2021-03-07 01:29:59.642125-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14fe5934836'
down_revision = '72a2413a6e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_coupons_per_user', sa.Integer(), nullable=True),
    sa.Column('hair_password', sa.String(), nullable=True),
    sa.Column('dress_password', sa.String(), nullable=True),
    sa.Column('makeup_password', sa.String(), nullable=True),
    sa.Column('email_template', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_config_id'), 'coupon_config', ['id'], unique=False)
    op.add_column('coupon', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('coupon', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('coupon', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('coupon', 'name')
    op.add_column('vendor', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('vendor', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('vendor', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vendor', 'last_name')
    op.drop_column('vendor', 'first_name')
    op.add_column('coupon', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('coupon', 'phone')
    op.drop_column('coupon', 'last_name')
    op.drop_column('coupon', 'first_name')
    op.drop_index(op.f('ix_coupon_config_id'), table_name='coupon_config')
    op.drop_table('coupon_config')
    # ### end Alembic commands ###
